POST http://localhost:3157/auth/register
Content-Type: application/json

{
    "username": "Test",
    "email": "test@email.com",
    "password": "testPass"
}

###

POST http://localhost:3157/auth/login
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "testPass"
}

###

GET http://localhost:3157